config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => { :registrations => "registrations", :sessions => "sessions"}
  resources :admins

  devise_scope :admin do
    get "/acceder" => "devise/sessions#new"
  end

  get 'bienes/index' => 'bienes#index', :as => :bienes

  get 'panel/panel' => 'panel#panel', :as => :panel
  get 'panel/principal' => 'panel#principal', :as => :panel_princ
  get 'panel/index' => 'panel#index', :as => :panel_index
  get 'panel/generar' => 'panel#generar', :as => :panel_nuevo
  get 'panel/editar' => 'panel#editar', :as => :panel_editar
  post 'panel' => 'panel#crear'
  get 'panel/:id' => 'panel#mostrar', :as => :panel_mostrar
  delete 'panel/:id' => 'panel#eliminar', :as => :panel_eliminar
  put 'panel/editar' => 'panel#actualizar'
  patch 'panel/editar' => 'panel#actualizar'
  put 'panel' => 'panel#actualizar'
  patch 'panel' => 'panel#actualizar'

  get '/' => 'principal#principal', :as => :main_es

  get '/catalogo_eventos' => 'principal#get_eventos', :as => :catalogo_eventos
  get '/cinta_eventos' => 'principal#cinta_eventos', :as => :cinta_eventos

  scope "(:locale)", locale: /(en)|(es)/ do
    get 'centros' => "centros_de_estudio#inicio", :as => :centros_de_estudio
    get 'ceaa' => "centros_de_estudio#ceaa", :as => :ceaa
    get 'cedua' => "centros_de_estudio#cedua", :as => :cedua
    get 'ceh' => "centros_de_estudio#ceh", :as => :ceh
    get 'cei' => "centros_de_estudio#cei", :as => :cei
    get 'cee' => "centros_de_estudio#cee", :as => :cee
    get 'cell' => "centros_de_estudio#cell", :as => :cell
    get 'ces' => "centros_de_estudio#ces", :as => :ces

    get 'programas' => "programas_academicos#inicio", :as => :programas_academicos
    get 'admisiones' => "programas_academicos#admisiones", :as => :admisiones
    get 'programas-docentes' => 'programas_academicos#programas', :as => :programas

    get 'convocatorias' => 'programas_academicos#convocatorias', :as => :convocatorias
    get 'proceso' => 'programas_academicos#proceso', :as => :proceso
    get "licenciaturas" => "programas_academicos#licenciaturas", :as => :licenciaturas
    get "maestrias" => "programas_academicos#maestrias", :as => :maestrias
    get "doctorados" => "programas_academicos#doctorados", :as => :doctorados
    get "cursos" => "programas_academicos#cursos", :as => :cursos_varios
    get 'catedras-seminarios' => "programas_academicos#catedras_y_seminarios", :as => :catedras_seminarios
    get "catedras" => "programas_academicos#catedras", :as => :cats
    get "seminarios" => "programas_academicos#seminarios", :as => :seminarios

    get 'autoridades' => 'informacion_general#autoridades', :as => :autoridades
    get 'profesores-emeritos' => 'informacion_general#profesores_emeritos', :as => :profesores_emeritos
    get 'historia' => 'informacion_general#historia', :as => :historia
    get 'sobre' => 'informacion_general#sobre_el_colegio', :as => :sobre_el_colegio
    get 'bienes' => 'informacion_general#bienes', :as => :bienes_part
    get 'licitaciones' => 'informacion_general#licitaciones', :as => :licitaciones
    get 'documentacion-institucional' => 'informacion_general#documentacion_institucional', :as => :documentacion
    get 'directorio-institucional' => 'informacion_general#directorio_institucional', :as => :dir_inst
    get 'actas' => 'informacion_general#actas', :as => :actas
    get 'informes' => 'informacion_general#informes', :as => :informes
    get 'estatutos' => 'informacion_general#estatutos', :as => :estatutos
    get 'asamblea' => 'informacion_general#asamblea', :as => :asamblea
    get 'junta' => 'informacion_general#junta', :as => :junta
    get 'presidencia' => 'informacion_general#presidencia', :as => :presidencia
    get 'centros_de_estudio' => 'informacion_general#centros_de_estudio', :as => :centros_autoridades
    get 'administracion' => 'informacion_general#administracion', :as => :administracion
    get 'apoyo' => 'informacion_general#unidades_de_apoyo', :as => :unidades_de_apoyo
    get "comision" => "informacion_general#comision", :as => :comision
    get "consejo" => "informacion_general#consejo", :as => :consejo
    get 'info_estudiantes' => 'informacion_general#informacion_para_estudiantes', :as => :info_estudiantes
    get 'operativas' => 'informacion_general#operativas', :as => :operativas
    get 'premios-distinciones' => 'informacion_general#premios_y_distinciones', :as => :premios
    get 'historia-75-aniversario' => 'informacion_general#historia_75_años', :as => :historia75
    get 'comunidad' => 'informacion_general#comunidad', :as => :otorgadoscomunidad
    get 'colegio' => 'informacion_general#colegio', :as => :otorgadoscolegio
    get 'directorio-academico' => 'informacion_general#directorio_academico_drive', :as => :directorio
    get 'marco-normativo' => 'informacion_general#marco_normativo', :as => :marco
    get 'presenciales' => 'programas_academicos#presenciales', :as => :presenciales
    get 'electronicos' => 'programas_academicos#electronicos', :as => :electronicos
    get 'dir-acad-test' => 'informacion_general#directorio_academico', :as => :dir

    get 'calendario-escolar' => 'programas_academicos#calendario_escolar', :as => :calendario

    get 'principios-eticos' => 'principal#principios_eticos', :as => :principios

    get 'resultados_busqueda' => 'principal#resultados_busqueda', :as => :busqueda

    get 'como-llegar' => 'principal#como_llegar', :as =>  :ubicacion

    get 'set_language' => 'principal#set_language', :as => :cambiar_idioma

    get 'directorio_academico_async' => 'informacion_general#directorio_academico_async', :as => :dir_async
    get 'recuperar_docentes' => 'informacion_general#recuperar_docentes', :as => :rec_doc

    get "mapa-sitio" => "principal#sitemap", :as => :sitemap
    get 'proximamente' => 'principal#proximamente', :as => :soon
    get 'aviso-privacidad' => 'principal#aviso_de_privacidad', :as => :aviso
    get 'aviso-completo' => 'principal#aviso_completo', :as => :priv
    get 'aviso-simple' => 'principal#aviso_simple', :as => :priv_simple

    scope "editable" do
      get 'sobre' => 'informacion_general#sobre_el_colegio', :as => :sobre_el_colegio_edit
      get 'historia' => 'informacion_general#historia', :as => :historia_edit
      get 'historia-75-aniversario' => 'informacion_general#historia_75_años', :as => :hist_75_edit
      get 'premios-distinciones' => 'informacion_general#premios_y_distinciones', :as => :premios_edit
      get 'principios-eticos' => 'principal#principios_eticos', :as => :principios_edit
      get 'bienes' => 'informacion_general#bienes', :as => :bienes_edit
      get 'centros' => "centros_de_estudio#inicio", :as => :centros_edit
      get 'programas' => "programas_academicos#inicio", :as => :programas_edit
      get "licenciaturas" => "programas_academicos#licenciaturas", :as => :licenciaturas_edit
      get "maestrias" => "programas_academicos#maestrias", :as => :maestrias_edit
      get "doctorados" => "programas_academicos#doctorados", :as => :doctorados_edit
      get "cursos" => "programas_academicos#cursos", :as => :cursos_edit
      get 'calendario-escolar' => 'programas_academicos#calendario_escolar', :as => :calendario_edit
      get 'admisiones' => "programas_academicos#admisiones", :as => :admisiones_edit
      get 'convocatorias' => 'programas_academicos#convocatorias', :as => :convocatorias_edit
      get 'proceso' => 'programas_academicos#proceso', :as => :proceso_edit
      get 'marco-normativo' => 'informacion_general#marco_normativo', :as => :marco_edit
      get 'autoridades' => 'informacion_general#autoridades', :as => :autoridades_edit
      get 'operativas' => 'informacion_general#operativas', :as => :operativas_edit
      get 'apoyo' => 'informacion_general#unidades_de_apoyo', :as => :unidades_de_apoyo_edit
      get 'administracion' => 'informacion_general#administracion', :as => :administracion_edit
      get 'centros_de_estudio' => 'informacion_general#centros_de_estudio', :as => :centros_autoridades_edit
      get "comision" => "informacion_general#comision", :as => :comision_edit
      get "consejo" => "informacion_general#consejo", :as => :consejo_edit
      get 'presidencia' => 'informacion_general#presidencia', :as => :presidencia_edit
      get 'junta' => 'informacion_general#junta', :as => :junta_edit
    end

  end
 
  get '/:locale' => 'principal#principal', :as => :main

  root to: "principal#principal"

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.label :usuario %><br />
    <%= f.text_field :usuario, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :admin %><br />
    <%= f.select(:admin, [['Administrador','Administrador'],['Editor','Editor'],['Responsable CEAA', 'Asia y África'], ['Responsable CEDUA', 'Demográficos, Urbanos y Ambientales'], ['Responsable CEE','Económicos'], ['Responsable CEH', 'Históricos'], ['Responsable CEI', 'Internacionales'], ['Responsable CELL', 'Lingüísticos y Literarios'], ['Responsable CES','Sociológicos']],:selected => (@admin.admin || 'Editor')) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<% if admin_signed_in? %>

<% if current_admin.admin == "Administrador" %>

<h1>Editing Admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

<% end %>
<% end %>

app/views/admins/index.html.erb
<% if admin_signed_in? %>

<% if current_admin.admin == "Administrador" %>

<p id="notice"><%= notice %></p>

<h1>Listing Admins</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Rol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
	<td><%= admin.usuario %></td>
        <td><%= admin.admin ? "Administrador" : "Creador de contenido" %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

<% end %>

<br>
<%= link_to "Regresar", panel_path %>

<% end %>

app/views/admins/new.html.erb
<% if admin_signed_in? %>

<% if current_admin.admin == "Administrador" %>

<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

<% end %>

<% end %>

app/views/admins/show.html.erb
<% if admin_signed_in? %>

<% if current_admin.admin == "Administrador" %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @admin.usuario %>
</p>

<p>
  <strong>Rol:</strong>
  <%= @admin.admin %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

<% end %>
<% end %>