config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => { :registrations => "registrations", :sessions => "sessions"}
  resources :admins

  devise_scope :admin do
    get "/acceder" => "devise/sessions#new"
  end

  get 'bienes/index' => 'bienes#index', :as => :bienes

  get 'panel/panel' => 'panel#panel', :as => :panel
  get 'panel/principal' => 'panel#principal', :as => :panel_princ
  get 'panel/index' => 'panel#index', :as => :panel_index
  get 'panel/generar' => 'panel#generar', :as => :panel_nuevo
  get 'panel/editar' => 'panel#editar', :as => :panel_editar
  post 'panel' => 'panel#crear'
  get 'panel/:id' => 'panel#mostrar', :as => :panel_mostrar
  delete 'panel/:id' => 'panel#eliminar', :as => :panel_eliminar
  put 'panel/editar' => 'panel#actualizar'
  patch 'panel/editar' => 'panel#actualizar'
  put 'panel' => 'panel#actualizar'
  patch 'panel' => 'panel#actualizar'

  get '/' => 'principal#principal', :as => :main_es

  get '/catalogo_eventos' => 'principal#get_eventos', :as => :catalogo_eventos
  get '/cinta_eventos' => 'principal#cinta_eventos', :as => :cinta_eventos

  scope "(:locale)", locale: /(en)|(es)/ do
    get 'centros' => "centros_de_estudio#inicio", :as => :centros_de_estudio
    get 'ceaa' => "centros_de_estudio#ceaa", :as => :ceaa
    get 'cedua' => "centros_de_estudio#cedua", :as => :cedua
    get 'ceh' => "centros_de_estudio#ceh", :as => :ceh
    get 'cei' => "centros_de_estudio#cei", :as => :cei
    get 'cee' => "centros_de_estudio#cee", :as => :cee
    get 'cell' => "centros_de_estudio#cell", :as => :cell
    get 'ces' => "centros_de_estudio#ces", :as => :ces

    get 'programas' => "programas_academicos#inicio", :as => :programas_academicos
    get 'admisiones' => "programas_academicos#admisiones", :as => :admisiones
    get 'programas-docentes' => 'programas_academicos#programas', :as => :programas

    get 'convocatorias' => 'programas_academicos#convocatorias', :as => :convocatorias
    get 'proceso' => 'programas_academicos#proceso', :as => :proceso
    get "licenciaturas" => "programas_academicos#licenciaturas", :as => :licenciaturas
    get "maestrias" => "programas_academicos#maestrias", :as => :maestrias
    get "doctorados" => "programas_academicos#doctorados", :as => :doctorados
    get "cursos" => "programas_academicos#cursos", :as => :cursos_varios
    get 'catedras-seminarios' => "programas_academicos#catedras_y_seminarios", :as => :catedras_seminarios
    get "catedras" => "programas_academicos#catedras", :as => :cats
    get "seminarios" => "programas_academicos#seminarios", :as => :seminarios

    get 'autoridades' => 'informacion_general#autoridades', :as => :autoridades
    get 'profesores-emeritos' => 'informacion_general#profesores_emeritos', :as => :profesores_emeritos
    get 'historia' => 'informacion_general#historia', :as => :historia
    get 'sobre' => 'informacion_general#sobre_el_colegio', :as => :sobre_el_colegio
    get 'bienes' => 'informacion_general#bienes', :as => :bienes_part
    get 'licitaciones' => 'informacion_general#licitaciones', :as => :licitaciones
    get 'documentacion-institucional' => 'informacion_general#documentacion_institucional', :as => :documentacion
    get 'directorio-institucional' => 'informacion_general#directorio_institucional', :as => :dir_inst
    get 'actas' => 'informacion_general#actas', :as => :actas
    get 'informes' => 'informacion_general#informes', :as => :informes
    get 'estatutos' => 'informacion_general#estatutos', :as => :estatutos
    get 'asamblea' => 'informacion_general#asamblea', :as => :asamblea
    get 'junta' => 'informacion_general#junta', :as => :junta
    get 'presidencia' => 'informacion_general#presidencia', :as => :presidencia
    get 'centros_de_estudio' => 'informacion_general#centros_de_estudio', :as => :centros_autoridades
    get 'administracion' => 'informacion_general#administracion', :as => :administracion
    get 'apoyo' => 'informacion_general#unidades_de_apoyo', :as => :unidades_de_apoyo
    get "comision" => "informacion_general#comision", :as => :comision
    get "consejo" => "informacion_general#consejo", :as => :consejo
    get 'info_estudiantes' => 'informacion_general#informacion_para_estudiantes', :as => :info_estudiantes
    get 'operativas' => 'informacion_general#operativas', :as => :operativas
    get 'premios-distinciones' => 'informacion_general#premios_y_distinciones', :as => :premios
    get 'historia-75-aniversario' => 'informacion_general#historia_75_años', :as => :historia75
    get 'comunidad' => 'informacion_general#comunidad', :as => :otorgadoscomunidad
    get 'colegio' => 'informacion_general#colegio', :as => :otorgadoscolegio
    get 'directorio-academico' => 'informacion_general#directorio_academico_drive', :as => :directorio
    get 'marco-normativo' => 'informacion_general#marco_normativo', :as => :marco
    get 'presenciales' => 'programas_academicos#presenciales', :as => :presenciales
    get 'electronicos' => 'programas_academicos#electronicos', :as => :electronicos
    get 'dir-acad-test' => 'informacion_general#directorio_academico', :as => :dir

    get 'calendario-escolar' => 'programas_academicos#calendario_escolar', :as => :calendario

    get 'principios-eticos' => 'principal#principios_eticos', :as => :principios

    get 'resultados_busqueda' => 'principal#resultados_busqueda', :as => :busqueda

    get 'como-llegar' => 'principal#como_llegar', :as =>  :ubicacion

    get 'set_language' => 'principal#set_language', :as => :cambiar_idioma

    get 'directorio_academico_async' => 'informacion_general#directorio_academico_async', :as => :dir_async
    get 'recuperar_docentes' => 'informacion_general#recuperar_docentes', :as => :rec_doc

    get "mapa-sitio" => "principal#sitemap", :as => :sitemap
    get 'proximamente' => 'principal#proximamente', :as => :soon
    get 'aviso-privacidad' => 'principal#aviso_de_privacidad', :as => :aviso
    get 'aviso-completo' => 'principal#aviso_completo', :as => :priv
    get 'aviso-simple' => 'principal#aviso_simple', :as => :priv_simple

    scope "editable" do
      get 'sobre' => 'informacion_general#sobre_el_colegio', :as => :sobre_el_colegio_edit
      get 'historia' => 'informacion_general#historia', :as => :historia_edit
      get 'historia-75-aniversario' => 'informacion_general#historia_75_años', :as => :hist_75_edit
      get 'premios-distinciones' => 'informacion_general#premios_y_distinciones', :as => :premios_edit
      get 'principios-eticos' => 'principal#principios_eticos', :as => :principios_edit
      get 'bienes' => 'informacion_general#bienes', :as => :bienes_edit
      get 'centros' => "centros_de_estudio#inicio", :as => :centros_edit
      get 'programas' => "programas_academicos#inicio", :as => :programas_edit
      get "licenciaturas" => "programas_academicos#licenciaturas", :as => :licenciaturas_edit
      get "maestrias" => "programas_academicos#maestrias", :as => :maestrias_edit
      get "doctorados" => "programas_academicos#doctorados", :as => :doctorados_edit
      get "cursos" => "programas_academicos#cursos", :as => :cursos_edit
      get 'calendario-escolar' => 'programas_academicos#calendario_escolar', :as => :calendario_edit
      get 'admisiones' => "programas_academicos#admisiones", :as => :admisiones_edit
      get 'convocatorias' => 'programas_academicos#convocatorias', :as => :convocatorias_edit
      get 'proceso' => 'programas_academicos#proceso', :as => :proceso_edit
      get 'marco-normativo' => 'informacion_general#marco_normativo', :as => :marco_edit
      get 'autoridades' => 'informacion_general#autoridades', :as => :autoridades_edit
      get 'operativas' => 'informacion_general#operativas', :as => :operativas_edit
      get 'apoyo' => 'informacion_general#unidades_de_apoyo', :as => :unidades_de_apoyo_edit
      get 'administracion' => 'informacion_general#administracion', :as => :administracion_edit
      get 'centros_de_estudio' => 'informacion_general#centros_de_estudio', :as => :centros_autoridades_edit
      get "comision" => "informacion_general#comision", :as => :comision_edit
      get "consejo" => "informacion_general#consejo", :as => :consejo_edit
      get 'presidencia' => 'informacion_general#presidencia', :as => :presidencia_edit
      get 'junta' => 'informacion_general#junta', :as => :junta_edit
    end

  end
 
  get '/:locale' => 'principal#principal', :as => :main

  root to: "principal#principal"

end

app/controllers/programas_academicos_controller.rb
class ProgramasAcademicosController < ApplicationController
  def inicio
    is_editable("Programas docentes")
    @licenciaturas = Curso.where(:programa => "Licenciatura").order(:titulo)
    @maestrias = Curso.where(:programa => "Maestría").order(:titulo)
    @doctorados = Curso.where(:programa => "Doctorado").order(:titulo)
  end

  def admisiones
    @licenciaturas = Curso.where(:programa => "Licenciatura").order(:titulo)
    @maestrias = Curso.where(:programa => "Maestría").order(:titulo)
    @doctorados = Curso.where(:programa => "Doctorado").order(:titulo)
  end

  def programas
    @licenciaturas = Curso.where(:programa => "Licenciatura").order(:titulo)
    @maestrias = Curso.where(:programa => "Maestría").order(:titulo)
    @doctorados = Curso.where(:programa => "Doctorado").order(:titulo)
    respond_to do |format|
      format.js
    end
  end

  def convocatorias
		@convocatorias = Curso.where("programa = ? AND fecha_fin_conv >= ? AND fecha_inicio_conv <= ?", "Licenciatura", Date.current(), Date.current()).union(Curso.where("programa = ? AND fecha_fin_conv >= ? AND fecha_inicio_conv <= ?", "Maestría", Date.current(), Date.current())).union(Curso.where("programa = ? AND fecha_fin_conv >= ? AND fecha_inicio_conv <= ?", "Doctorado", Date.current(), Date.current())).union(Curso.where("programa = ? AND fecha_fin_conv >= ? AND fecha_inicio_conv <= ?", "Curso", Date.current(), Date.current())).order(:titulo)
    respond_to do |format|
      format.js
    end
  end

  def proceso
    is_editable("Admisiones (proceso)")
    respond_to do |format|
      format.js
    end
  end

  def calendario_escolar
    is_editable("Calendario escolar")
  end

  def maestrias
    is_editable("Maestrías")
    @maestrias = Curso.where(:programa => "Maestría").order(:titulo)
  end

  def licenciaturas
    is_editable("Licenciaturas")
    @licenciaturas = Curso.where(:programa => "Licenciatura").order(:titulo)
  end

  def doctorados
    is_editable("Doctorados")
    @doctorados = Curso.where(:programa => "Doctorado").order(:titulo)
  end

  def cursos
    is_editable("Cursos")
    @electronicos = Curso.where("programa = ? AND tipo_curso = ?", "Curso", "En línea")
    @presenciales = Curso.where("programa = ? AND tipo_curso = ? and fecha_fin_conv >= ?", "Curso", "Presencial", Date.current())
  end

  def presenciales
    @presenciales = Curso.where("programa = ? AND tipo_curso = ? and fecha_fin_conv >= ?", "Curso", "Presencial", Date.current())
    respond_to do |format|
      format.js
    end
  end

  def electronicos
    @electronicos = Curso.where("programa = ? AND tipo_curso = ?", "Curso", "En línea")
    respond_to do |format|
      format.js
    end
  end

  def catedras_y_seminarios
		@centros = Catedra.distinct.pluck(:tipo)
    @catedras = Catedra.where(("tipo = ? AND " + (params[:locale] == "en" ? "titulo_eng" : "titulo") + " != ''"), "Institucionales")
  end

  def catedras
    @catedras = Catedra.where(("tipo = ? AND " + (params[:locale] == "en" ? "titulo_eng" : "titulo") + " != ''"), params[:grupo])
    respond_to do |format|
      format.js
    end
  end

  def seminarios
    @seminarios = Catedra.where("tipo = ? AND titulo LIKE ?", "Seminario", "%Violencia y Paz%").union(Catedra.where("tipo = ? AND titulo LIKE ?", "Seminario", "%México-España%")).union(Catedra.where("tipo = ? AND titulo LIKE ?", "Seminario", "%Diálogos%")).union(Catedra.where("tipo = ? AND titulo LIKE ?", "Seminario", "%Intelectual%")).union(Catedra.where("tipo = ? AND titulo LIKE ?", "Seminario", "%Historiografía%")).union(Catedra.where("tipo = ? AND titulo LIKE ?", "Seminario", "%Historia Económica%")).union(Catedra.where("tipo = ? AND titulo LIKE ?", "Seminario", "%7 Tesis%")).union(Catedra.where("tipo = ? AND titulo LIKE ?", "Seminario", "%Historia Social%")).union(Catedra.where("tipo = ? AND titulo LIKE ?", "Seminario", "%Historia Internacional%")).union(Catedra.where("tipo = ? AND titulo LIKE ?", "Seminario", "%Formación Política%")).union(Catedra.where("tipo = ? AND titulo LIKE ?", "Seminario", "%Migración Internacional%"))
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/programas_academicos_helper.rb
module ProgramasAcademicosHelper
end

app/views/programas_academicos/_inicio.html.erb
<div class="container-fluid" id="resto-cuerpo">
	<div id="cuerpo" class="principal-chica uk-block-large">
	
    <div class="uk-width-1-1">
    <span class="titulo-grande"><%= t('botones.b3.texto') %></span><br>
    <p>&nbsp;</p>
    <!--          Aquí empieza el contenido          -->
    <div class="uk-grid uk-grid-large uk-margin-large-bottom">
    <div class="uk-width-large-3-5">
    <img src="<%= image_url(@pics[0].foto.url) %>" alt="Licenciaturas">
    </div>
    <div class="uk-width-large-2-5 uk-text-left">
    <span class="titulo-chico"><%= t('programas.licenciaturas') %></span><br>

    <ul class=" uk-list uk-list-space">
		<% Curso.where(:programa => "Licenciatura").order(:titulo).each do |lic| %>
		  <li class="uk-link sin-pointer"><%= (params[:locale] == "es" ? lic.titulo.gsub(/<(\/)?div>/,"").html_safe : lic.traduccion_tit.gsub(/<(\/)?div>/,"").html_safe)%></li>
		<% end %>
    </ul>
		<a href=<%= licenciaturas_path %> class="ver-mas uk-margin-large-bottom uk-button-small"><%= t('programas.mas') %></a>
    </div>
    </div>
    <div class="uk-grid uk-grid-large uk-margin-large-bottom">
    <div class="uk-width-large-3-5">
    <img src="<%= image_url(@pics[1].foto.url) %>" alt="Maestrías">
    </div>
    <div class="uk-width-large-2-5 uk-text-left">
    <span class="titulo-chico"><%= t('programas.maestrias') %></span><br>

    <ul class=" uk-list uk-list-space">
    <% Curso.where(:programa => "Maestría").order(:titulo).each do |mt| %>
		  <li class="uk-link sin-pointer"><%= (params[:locale] == "es" ? mt.titulo.gsub(/<(\/)?div>/,"").html_safe : mt.traduccion_tit.gsub(/<(\/)?div>/,"").html_safe) %></li>
		<% end %>
    </ul>
	<a href=<%= maestrias_path %> class="ver-mas uk-margin-large-bottom uk-button-small"><%= t('programas.mas') %></a>
    </div>
    </div>
    <div class="uk-grid uk-grid-large uk-margin-large-bottom">
    <div class="uk-width-large-3-5">
    <img src="<%= image_url(@pics[2].foto.url) %>" alt="Doctorados">
    </div>
    <div class="uk-width-large-2-5 uk-text-left">
    <span class="titulo-chico"><%= t('programas.doctorados') %></span><br>

    <ul class=" uk-list uk-list-space">
    <% Curso.where(:programa => "Doctorado").order(:titulo).each do |doc| %>
		  <li class="uk-link sin-pointer"><%= (params[:locale] == "es" ? doc.titulo.gsub(/<(\/)?div>/,"").html_safe : doc.traduccion_tit.gsub(/<(\/)?div>/,"").html_safe) %></li>
		<% end %>
    </ul>
		<a href=<%= doctorados_path %> class="ver-mas uk-margin-large-bottom uk-button-small"><%= t('programas.mas') %></a>
    </div>
    </div>
    </div>

	</div>

</div>

app/views/programas_academicos/_programas.html.erb
<div>
<span class="titulo-chico"><%= params[:locale] == "en" ? "B.A. Programs" : "Licenciaturas" %></span><br>

    <ul class=" uk-list uk-list-space">
		<% @licenciaturas.each do |lic| %>
		  <li class="uk-link sin-pointer"><%= params[:locale] == "en" ? lic.traduccion_tit.gsub(/<(\/)?div>/,"").html_safe : lic.titulo.gsub(/<(\/)?div>/,"").html_safe %></li>
		<% end %>
    </ul>
		<a href=<%= licenciaturas_path %> class="ver-mas uk-margin-large-bottom uk-button-small"><%= params[:locale] == "en" ? "More information" : "Conoce más" %></a>
</div>

<div>
<span class="titulo-chico"><%= params[:locale] == "en" ? "Master's programs" : "Maestrías" %></span><br>

    <ul class=" uk-list uk-list-space">
    <% @maestrias.each do |mt| %>
		  <li class="uk-link sin-pointer"><%= params[:locale] == "en" ? mt.traduccion_tit.gsub(/<(\/)?div>/,"").html_safe : mt.titulo.gsub(/<(\/)?div>/,"").html_safe %></li>
		<% end %>
    </ul>
	<a href=<%= maestrias_path %> class="ver-mas uk-margin-large-bottom uk-button-small"><%= params[:locale] == "en" ? "More information" : "Conoce más" %></a>
</div>

<div>
<span class="titulo-chico"><%= params[:locale] == "en" ? "Doctoral programs" : "Doctorados" %></span><br>
		<ul class=" uk-list uk-list-space">
    <% @doctorados.each do |doc| %>
		  <li class="uk-link sin-pointer"><%= params[:locale] == "en" ? doc.traduccion_tit.gsub(/<(\/)?div>/,"").html_safe : doc.titulo.gsub(/<(\/)?div>/,"").html_safe %></li>
		<% end %>
    </ul>
		<a href=<%= doctorados_path %> class="ver-mas uk-margin-large-bottom uk-button-small"><%= params[:locale] == "en" ? "More information" : "Conoce más" %></a>
</div>

app/views/programas_academicos/catedras.js.erb
$("#titulo-render").html("<%= params[:grupo] == "Institucionales" && params[:locale] == "en" ? "Institutional" : params[:grupo] %>");
$("#cats-render").html("<%= j render :partial => 'catedras' %>");

app/views/programas_academicos/cursos.html.erb
<%= render 'principal/barra' %>
<div class="container-fluid" id="resto-cuerpo">
	<div id="cuerpo" class="principal uk-block-large">

<% if @editable %>
<%= form_for(@sitio, :url => {:controller => "panel", :action => "editar", :params => {:set => "Contenido de sitios", :id => @sitio.id}, :uri => request.original_fullpath.gsub(/editable\//,"")}, :html => { :multipart => true }) do |f| %>
  <% if @sitio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sitio.errors.count, "error") %> impidieron generar este objeto:</h2>

      <ul>
      <% @sitio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

    <div class="uk-width-1-1">
        <span class="titulo-grande"><%= t('botones.b3.opciones.op6') %></span><br>
    <div class="uk-container-center uk-block">
<%= fields_for 'pics[]', @pics[0] do |p| %>
		<br>
		<%= image_tag(@pics[0].foto.url, id: "foto_1") %>
		<br>
				<%= p.label :foto, raw('<span class="glyphicon glyphicon-upload glyph-padding"></span>Añadir foto') %><br>
				<%= p.file_field :foto, :onchange => "readURL(this,'#foto_1')" %><br>

		<div class="field">
				<%= p.label (params[:locale] == "es" ? :caption : :caption_ingles), "Pie de foto (Foto " + ((@pics[0].f_ind+1).to_s) + ")" %><br>
				<%= p.trix_editor (params[:locale] == "es" ? :caption : :caption_ingles), value: (params[:locale] == "es" ? @pics[0].caption.gsub(/<(((\/)?p)|(br))>/,"").html_safe : @pics[0].caption_ingles.gsub(/<(((\/)?p)|(br))>/,"").html_safe ) %>
		</div>
<% end %>
		</div>
    <p>&nbsp;</p>
    <div class="uk-grid uk-grid-medium">
    <div class="uk-width-large-1-5 uk-text-center-small uk-text-center-medium uk-text-left" style="border-right:2px solid #EEEEEE;">
    <!--          Aquí empieza el menú pequeño          -->
    <ul style="text-align:left;">

			<% if @presenciales.count > 0 %>
      <li style="list-style-type:none; margin-bottom:5px;"><%= link_to(image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + (params[:locale] == "en" ? "Short courses" : "Presenciales"), presenciales_path, :remote => true, :class => "link-sobre", :id => "presencial-link") %></li>
			<% end %>
			<% if params[:locale] != "en" %>

			<% if false %>
      <li style="list-style-type:none; margin-bottom:5px;"><%= link_to image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + (params[:locale] == "en" ? "Massive online courses" : "En línea"), electronicos_path, :remote => true, :class => "link-sobre", :id => "electronico-link" %></li>
			<% end %>
      <li style="list-style-type:none; margin-bottom:5px;"><%= link_to image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + "MOOCs", electronicos_path(tipo: "MOOC"), :remote => true, :class => "link-sobre", :id => "electronico-link" %></li>
      <li style="list-style-type:none; margin-bottom:5px;"><%= link_to image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + "Cursos breves", electronicos_path(tipo: "Breve"), :remote => true, :class => "link-sobre", :id => "electronico-link" %></li>
			<% end %>
    </ul>
    </div>

    <div class="uk-width-large-4-5">
    <span class="titulo-chico morado" id="titulo-render"><%= params[:locale] == "en" ? (@presenciales.count > 0 ? "Short courses" : "") : (@presenciales.count > 0 ? "Cursos presenciales" : "Cursos en línea") %></span><br>

    <div id="cursos-render">
    	<%= render (@presenciales.size > 0 ? 'programas_academicos/presenciales' : 'programas_academicos/electronicos'), params: {tipo: (params[:locale] == "es" ? 'MOOC' : '')} %>
			<% if params[:locale] == "en" && @presenciales.size == 0 %>
				No available content at this moment.
			<% end %>
    </div>
    </div>
    </div>
    </div>

<br>
<div class="actions">
<%= f.submit "Guardar cambios" %>
</div>

<% end %>

<% else %>

    <div class="uk-width-1-1">
        <span class="titulo-grande"><%= t('botones.b3.opciones.op6') %></span><br>
    <div class="uk-container-center uk-block"><img src="<%= image_url(@pics[0].foto.url.include?('vacio') ? 'cursos.jpg' : @pics[0].foto.url) %>" alt="Cursos"></div>
    <p>&nbsp;</p>
    <div class="uk-grid uk-grid-medium">
    <div class="uk-width-large-1-5 uk-text-center-small uk-text-center-medium uk-text-left" style="border-right:2px solid #EEEEEE;">
    <!--          Aquí empieza el menú pequeño          -->
    <ul style="text-align:left;">

			<% if @presenciales.count > 0 %>
      <li style="list-style-type:none; margin-bottom:5px;"><%= link_to(image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + (params[:locale] == "en" ? "Short courses" : "Presenciales"), presenciales_path, :remote => true, :class => "link-sobre", :id => "presencial-link") %></li>
			<% end %>
			<% if params[:locale] != "en" %>

			<% if false %>
      <li style="list-style-type:none; margin-bottom:5px;"><%= link_to image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + (params[:locale] == "en" ? "Massive online courses" : "En línea"), electronicos_path, :remote => true, :class => "link-sobre", :id => "electronico-link" %></li>
			<% end %>
      <li style="list-style-type:none; margin-bottom:5px;"><%= link_to image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + "MOOCs", electronicos_path(tipo: "MOOC"), :remote => true, :class => "link-sobre", :id => "electronico-link" %></li>
      <li style="list-style-type:none; margin-bottom:5px;"><%= link_to image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + "Cursos breves", electronicos_path(tipo: "Breve"), :remote => true, :class => "link-sobre", :id => "electronico-link" %></li>
			<% end %>
    </ul>
    </div>

    <div class="uk-width-large-4-5">
    <span class="titulo-chico morado" id="titulo-render"><%= params[:locale] == "en" ? (@presenciales.count > 0 ? "Short courses" : "") : (@presenciales.count > 0 ? "Cursos presenciales" : "Cursos en línea") %></span><br>

    <div id="cursos-render">
    	<%= render (@presenciales.size > 0 ? 'programas_academicos/presenciales' : 'programas_academicos/electronicos'), params: {tipo: (params[:locale] == "es" ? 'MOOC' : '')} %>
			<% if params[:locale] == "en" && @presenciales.size == 0 %>
				No available content at this moment.
			<% end %>
    </div>
    </div>
    </div>
    </div>

<% end %>

	</div>
<%= render 'principal/footer'%>

app/views/programas_academicos/seminarios.js.erb
$("#titulo-render").html("<%= "Seminarios" %>");
$("#cats-render").html("<%= j render :partial => 'seminarios' %>");