config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => { :registrations => "registrations", :sessions => "sessions"}
  resources :admins

  devise_scope :admin do
    get "/acceder" => "devise/sessions#new"
  end

  get 'bienes/index' => 'bienes#index', :as => :bienes

  get 'panel/panel' => 'panel#panel', :as => :panel
  get 'panel/principal' => 'panel#principal', :as => :panel_princ
  get 'panel/index' => 'panel#index', :as => :panel_index
  get 'panel/generar' => 'panel#generar', :as => :panel_nuevo
  get 'panel/editar' => 'panel#editar', :as => :panel_editar
  post 'panel' => 'panel#crear'
  get 'panel/:id' => 'panel#mostrar', :as => :panel_mostrar
  delete 'panel/:id' => 'panel#eliminar', :as => :panel_eliminar
  put 'panel/editar' => 'panel#actualizar'
  patch 'panel/editar' => 'panel#actualizar'
  put 'panel' => 'panel#actualizar'
  patch 'panel' => 'panel#actualizar'

  get '/' => 'principal#principal', :as => :main_es

  get '/catalogo_eventos' => 'principal#get_eventos', :as => :catalogo_eventos
  get '/cinta_eventos' => 'principal#cinta_eventos', :as => :cinta_eventos

  scope "(:locale)", locale: /(en)|(es)/ do
    get 'centros' => "centros_de_estudio#inicio", :as => :centros_de_estudio
    get 'ceaa' => "centros_de_estudio#ceaa", :as => :ceaa
    get 'cedua' => "centros_de_estudio#cedua", :as => :cedua
    get 'ceh' => "centros_de_estudio#ceh", :as => :ceh
    get 'cei' => "centros_de_estudio#cei", :as => :cei
    get 'cee' => "centros_de_estudio#cee", :as => :cee
    get 'cell' => "centros_de_estudio#cell", :as => :cell
    get 'ces' => "centros_de_estudio#ces", :as => :ces

    get 'programas' => "programas_academicos#inicio", :as => :programas_academicos
    get 'admisiones' => "programas_academicos#admisiones", :as => :admisiones
    get 'programas-docentes' => 'programas_academicos#programas', :as => :programas

    get 'convocatorias' => 'programas_academicos#convocatorias', :as => :convocatorias
    get 'proceso' => 'programas_academicos#proceso', :as => :proceso
    get "licenciaturas" => "programas_academicos#licenciaturas", :as => :licenciaturas
    get "maestrias" => "programas_academicos#maestrias", :as => :maestrias
    get "doctorados" => "programas_academicos#doctorados", :as => :doctorados
    get "cursos" => "programas_academicos#cursos", :as => :cursos_varios
    get 'catedras-seminarios' => "programas_academicos#catedras_y_seminarios", :as => :catedras_seminarios
    get "catedras" => "programas_academicos#catedras", :as => :cats
    get "seminarios" => "programas_academicos#seminarios", :as => :seminarios

    get 'autoridades' => 'informacion_general#autoridades', :as => :autoridades
    get 'profesores-emeritos' => 'informacion_general#profesores_emeritos', :as => :profesores_emeritos
    get 'historia' => 'informacion_general#historia', :as => :historia
    get 'sobre' => 'informacion_general#sobre_el_colegio', :as => :sobre_el_colegio
    get 'bienes' => 'informacion_general#bienes', :as => :bienes_part
    get 'licitaciones' => 'informacion_general#licitaciones', :as => :licitaciones
    get 'documentacion-institucional' => 'informacion_general#documentacion_institucional', :as => :documentacion
    get 'directorio-institucional' => 'informacion_general#directorio_institucional', :as => :dir_inst
    get 'actas' => 'informacion_general#actas', :as => :actas
    get 'informes' => 'informacion_general#informes', :as => :informes
    get 'estatutos' => 'informacion_general#estatutos', :as => :estatutos
    get 'asamblea' => 'informacion_general#asamblea', :as => :asamblea
    get 'junta' => 'informacion_general#junta', :as => :junta
    get 'presidencia' => 'informacion_general#presidencia', :as => :presidencia
    get 'centros_de_estudio' => 'informacion_general#centros_de_estudio', :as => :centros_autoridades
    get 'administracion' => 'informacion_general#administracion', :as => :administracion
    get 'apoyo' => 'informacion_general#unidades_de_apoyo', :as => :unidades_de_apoyo
    get "comision" => "informacion_general#comision", :as => :comision
    get "consejo" => "informacion_general#consejo", :as => :consejo
    get 'info_estudiantes' => 'informacion_general#informacion_para_estudiantes', :as => :info_estudiantes
    get 'operativas' => 'informacion_general#operativas', :as => :operativas
    get 'premios-distinciones' => 'informacion_general#premios_y_distinciones', :as => :premios
    get 'historia-75-aniversario' => 'informacion_general#historia_75_años', :as => :historia75
    get 'comunidad' => 'informacion_general#comunidad', :as => :otorgadoscomunidad
    get 'colegio' => 'informacion_general#colegio', :as => :otorgadoscolegio
    get 'directorio-academico' => 'informacion_general#directorio_academico_drive', :as => :directorio
    get 'marco-normativo' => 'informacion_general#marco_normativo', :as => :marco
    get 'presenciales' => 'programas_academicos#presenciales', :as => :presenciales
    get 'electronicos' => 'programas_academicos#electronicos', :as => :electronicos
    get 'dir-acad-test' => 'informacion_general#directorio_academico', :as => :dir

    get 'calendario-escolar' => 'programas_academicos#calendario_escolar', :as => :calendario

    get 'principios-eticos' => 'principal#principios_eticos', :as => :principios

    get 'resultados_busqueda' => 'principal#resultados_busqueda', :as => :busqueda

    get 'como-llegar' => 'principal#como_llegar', :as =>  :ubicacion

    get 'set_language' => 'principal#set_language', :as => :cambiar_idioma

    get 'directorio_academico_async' => 'informacion_general#directorio_academico_async', :as => :dir_async
    get 'recuperar_docentes' => 'informacion_general#recuperar_docentes', :as => :rec_doc

    get "mapa-sitio" => "principal#sitemap", :as => :sitemap
    get 'proximamente' => 'principal#proximamente', :as => :soon
    get 'aviso-privacidad' => 'principal#aviso_de_privacidad', :as => :aviso
    get 'aviso-completo' => 'principal#aviso_completo', :as => :priv
    get 'aviso-simple' => 'principal#aviso_simple', :as => :priv_simple

    scope "editable" do
      get 'sobre' => 'informacion_general#sobre_el_colegio', :as => :sobre_el_colegio_edit
      get 'historia' => 'informacion_general#historia', :as => :historia_edit
      get 'historia-75-aniversario' => 'informacion_general#historia_75_años', :as => :hist_75_edit
      get 'premios-distinciones' => 'informacion_general#premios_y_distinciones', :as => :premios_edit
      get 'principios-eticos' => 'principal#principios_eticos', :as => :principios_edit
      get 'bienes' => 'informacion_general#bienes', :as => :bienes_edit
      get 'centros' => "centros_de_estudio#inicio", :as => :centros_edit
      get 'programas' => "programas_academicos#inicio", :as => :programas_edit
      get "licenciaturas" => "programas_academicos#licenciaturas", :as => :licenciaturas_edit
      get "maestrias" => "programas_academicos#maestrias", :as => :maestrias_edit
      get "doctorados" => "programas_academicos#doctorados", :as => :doctorados_edit
      get "cursos" => "programas_academicos#cursos", :as => :cursos_edit
      get 'calendario-escolar' => 'programas_academicos#calendario_escolar', :as => :calendario_edit
      get 'admisiones' => "programas_academicos#admisiones", :as => :admisiones_edit
      get 'convocatorias' => 'programas_academicos#convocatorias', :as => :convocatorias_edit
      get 'proceso' => 'programas_academicos#proceso', :as => :proceso_edit
      get 'marco-normativo' => 'informacion_general#marco_normativo', :as => :marco_edit
      get 'autoridades' => 'informacion_general#autoridades', :as => :autoridades_edit
      get 'operativas' => 'informacion_general#operativas', :as => :operativas_edit
      get 'apoyo' => 'informacion_general#unidades_de_apoyo', :as => :unidades_de_apoyo_edit
      get 'administracion' => 'informacion_general#administracion', :as => :administracion_edit
      get 'centros_de_estudio' => 'informacion_general#centros_de_estudio', :as => :centros_autoridades_edit
      get "comision" => "informacion_general#comision", :as => :comision_edit
      get "consejo" => "informacion_general#consejo", :as => :consejo_edit
      get 'presidencia' => 'informacion_general#presidencia', :as => :presidencia_edit
      get 'junta' => 'informacion_general#junta', :as => :junta_edit
    end

  end
 
  get '/:locale' => 'principal#principal', :as => :main

  root to: "principal#principal"

end

app/controllers/sobre_el_colegio_controller.rb
class SobreElColegioController < ApplicationController

  def historia_75_años
  end

  def premios_y_distinciones
    @categorias = Categorium.all
  end

  def documentacion_institucional
    @actas = Documento.where(:tipo => "Junta")
  end

  def actas
    @actas = Documento.where(:tipo => "Junta")
    respond_to do |format|
      format.js
    end
  end

  def informes
    @informes = Documento.where(:tipo => "Informe")
    respond_to do |format|
      format.js
    end
  end

  def estatutos
    @estatutos = Documento.where(:tipo => "Estatuto")
    respond_to do |format|
      format.js
    end
  end

  def historia
    @estatuto_organico = Documento.where("tipo = ? AND nombre LIKE ?","Estatuto","%Orgánico%").first
  end

  def autoridades
    @actas = Documento.where(:tipo => "Junta")
  end

  def profesores_emeritos
    @profesores = Emerito.all
  end

  def informacion_general
  end

  def asamblea
    respond_to do |format|
      format.js
    end
  end

  def operativas
    @operativas = Personal.where(:seccion => "Operativas")
    respond_to do |format|
      format.js
    end
  end

  def junta
    @juntas = Personal.where(:seccion => "Junta")
    respond_to do |format|
      format.js
    end
  end

  def presidencia
    @presidencias = Personal.where(:seccion => "Presidencia")
    respond_to do |format|
      format.js
    end
  end

  def centros_de_estudio
    @centros = Personal.where(:seccion => "Centros")
    respond_to do |format|
      format.js
    end
  end

  def administracion
    @admins = Personal.where(:seccion => "Administración")
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/sobre_el_colegio_helper.rb
module SobreElColegioHelper

  def construye_cursos(tipo_programa)
    bloque_html, i = "", 1
    Curso.where(programa: tipo_programa).each do |p|
      bloque_html = bloque_html + "<p>" + i.to_s + ".- " + (params[:locale] == "sp" ? p.titulo : p.traduccion_tit) + ". " + (params[:locale] == "sp" ? p.descripcion : p.traduccion_desc) + "</p>"
      i = i + 1
    end
    return bloque_html.html_safe
  end
end

app/views/sobre_el_colegio/informacion_general.html.erb
<%= render 'principal/barra' %>
<div class="container-fluid" id="resto-cuerpo">
	<div id="cuerpo" class="principal-chica uk-block-large">

<div class="uk-width-1-1">
    <div class="uk-grid uk-grid-small">
    <div class="uk-width-large-3-5 uk-text-center-small uk-text-center-medium uk-text-left">
    <img src=<%= image_url("sobre-el-colegio.jpg") %> alt="Historia de El Colegio de México">
    <p>&nbsp;</p>
    <!--          Aquí empieza el menú pequeño          -->
    <div class="uk-hidden-medium uk-hidden-small">
    <ul class="lista-links" style="text-align:left;">
<li><%= construir_link("bt-flechita.png", "bt-flechita-hover.png", "Centros de Estudio",centros_de_estudio_url,"link-sobre",false) %></li>
					<li><%= construir_link("bt-flechita.png", "bt-flechita-hover.png","Publicaciones","http://libros.colmex.mx/","link-sobre") %></li>
					<li><%= construir_link("bt-flechita.png", "bt-flechita-hover.png","Revistas","http://revistas.colmex.mx/","link-sobre") %></li>
					<li><%= construir_link("bt-flechita.png", "bt-flechita-hover.png","Programa de Educación Digital","http://digital.colmex.mx/","link-sobre") %></li>
    </ul>
    </div>
    <!--          Aquí termina el menú pequeño          -->
    </div>
    <div class="uk-width-large-2-5">
    <span class="titulo-chico">Sobre</span><br>
    <span class="titulo-grande">El Colegio de México</span><br>
    <p>El Colegio de México es una institución pública, de carácter universitario, dedicada a la investigación y a la enseñanza superior en ciencias sociales y humanidades, siendo una de los más destacadas en el mundo hispánico, por lo cual ha recibido numerosos reconocimientos desde su fundación en 1940 hasta el presente.</p>
    <p>Para cumplir con sus fines El Colegio de México lleva a cabo investigaciones y docencia en las áreas de la especialidad de los Centros de Estudios que lo integran: Históricos, Lingüísticos y Literarios, Internacionales, de Asia y África, Económicos, Demográficos Urbanos y Ambientales, y Sociológicos,además de programas de Estudios de Género, Traducción y Bibliotecología. Ofrece licenciaturas, maestrías y doctorados por especialidad, así como cursos de especialización y de verano.</p>
    <p>El Colegio cuenta con cuenta con una gran Biblioteca, especializada en ciencias sociales y humanidades abierta al público. Su acervo está constituido por más de 700,000 volúmenes y cuenta con una enorme cantidad de recursos electrónicos y digitales.  Asimismo, la institución  cuenta con las unidades del Departamento de Publicaciones,  Programa de Educación Digital, y Coordinación de Servicios de Cómputo.</p>
    <p>De las aulas de El Colegio han salido varios millares de egresados que se han destacado en la investigación, la docencia, la función pública y otros campos de actividad profesional en México y en numerosos países del mundo.</p>
    <p>&nbsp;</p>
    </div>
    </div>
    </div> 


		
	</div>

<%= render 'principal/footer'%>