config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => { :registrations => "registrations", :sessions => "sessions"}
  resources :admins

  devise_scope :admin do
    get "/acceder" => "devise/sessions#new"
  end

  get 'bienes/index' => 'bienes#index', :as => :bienes

  get 'panel/panel' => 'panel#panel', :as => :panel
  get 'panel/principal' => 'panel#principal', :as => :panel_princ
  get 'panel/index' => 'panel#index', :as => :panel_index
  get 'panel/generar' => 'panel#generar', :as => :panel_nuevo
  get 'panel/editar' => 'panel#editar', :as => :panel_editar
  post 'panel' => 'panel#crear'
  get 'panel/:id' => 'panel#mostrar', :as => :panel_mostrar
  delete 'panel/:id' => 'panel#eliminar', :as => :panel_eliminar
  put 'panel/editar' => 'panel#actualizar'
  patch 'panel/editar' => 'panel#actualizar'
  put 'panel' => 'panel#actualizar'
  patch 'panel' => 'panel#actualizar'

  get '/' => 'principal#principal', :as => :main_es

  get '/catalogo_eventos' => 'principal#get_eventos', :as => :catalogo_eventos
  get '/cinta_eventos' => 'principal#cinta_eventos', :as => :cinta_eventos

  scope "(:locale)", locale: /(en)|(es)/ do
    get 'centros' => "centros_de_estudio#inicio", :as => :centros_de_estudio
    get 'ceaa' => "centros_de_estudio#ceaa", :as => :ceaa
    get 'cedua' => "centros_de_estudio#cedua", :as => :cedua
    get 'ceh' => "centros_de_estudio#ceh", :as => :ceh
    get 'cei' => "centros_de_estudio#cei", :as => :cei
    get 'cee' => "centros_de_estudio#cee", :as => :cee
    get 'cell' => "centros_de_estudio#cell", :as => :cell
    get 'ces' => "centros_de_estudio#ces", :as => :ces

    get 'programas' => "programas_academicos#inicio", :as => :programas_academicos
    get 'admisiones' => "programas_academicos#admisiones", :as => :admisiones
    get 'programas-docentes' => 'programas_academicos#programas', :as => :programas

    get 'convocatorias' => 'programas_academicos#convocatorias', :as => :convocatorias
    get 'proceso' => 'programas_academicos#proceso', :as => :proceso
    get "licenciaturas" => "programas_academicos#licenciaturas", :as => :licenciaturas
    get "maestrias" => "programas_academicos#maestrias", :as => :maestrias
    get "doctorados" => "programas_academicos#doctorados", :as => :doctorados
    get "cursos" => "programas_academicos#cursos", :as => :cursos_varios
    get 'catedras-seminarios' => "programas_academicos#catedras_y_seminarios", :as => :catedras_seminarios
    get "catedras" => "programas_academicos#catedras", :as => :cats
    get "seminarios" => "programas_academicos#seminarios", :as => :seminarios

    get 'autoridades' => 'informacion_general#autoridades', :as => :autoridades
    get 'profesores-emeritos' => 'informacion_general#profesores_emeritos', :as => :profesores_emeritos
    get 'historia' => 'informacion_general#historia', :as => :historia
    get 'sobre' => 'informacion_general#sobre_el_colegio', :as => :sobre_el_colegio
    get 'bienes' => 'informacion_general#bienes', :as => :bienes_part
    get 'licitaciones' => 'informacion_general#licitaciones', :as => :licitaciones
    get 'documentacion-institucional' => 'informacion_general#documentacion_institucional', :as => :documentacion
    get 'directorio-institucional' => 'informacion_general#directorio_institucional', :as => :dir_inst
    get 'actas' => 'informacion_general#actas', :as => :actas
    get 'informes' => 'informacion_general#informes', :as => :informes
    get 'estatutos' => 'informacion_general#estatutos', :as => :estatutos
    get 'asamblea' => 'informacion_general#asamblea', :as => :asamblea
    get 'junta' => 'informacion_general#junta', :as => :junta
    get 'presidencia' => 'informacion_general#presidencia', :as => :presidencia
    get 'centros_de_estudio' => 'informacion_general#centros_de_estudio', :as => :centros_autoridades
    get 'administracion' => 'informacion_general#administracion', :as => :administracion
    get 'apoyo' => 'informacion_general#unidades_de_apoyo', :as => :unidades_de_apoyo
    get "comision" => "informacion_general#comision", :as => :comision
    get "consejo" => "informacion_general#consejo", :as => :consejo
    get 'info_estudiantes' => 'informacion_general#informacion_para_estudiantes', :as => :info_estudiantes
    get 'operativas' => 'informacion_general#operativas', :as => :operativas
    get 'premios-distinciones' => 'informacion_general#premios_y_distinciones', :as => :premios
    get 'historia-75-aniversario' => 'informacion_general#historia_75_años', :as => :historia75
    get 'comunidad' => 'informacion_general#comunidad', :as => :otorgadoscomunidad
    get 'colegio' => 'informacion_general#colegio', :as => :otorgadoscolegio
    get 'directorio-academico' => 'informacion_general#directorio_academico_drive', :as => :directorio
    get 'marco-normativo' => 'informacion_general#marco_normativo', :as => :marco
    get 'presenciales' => 'programas_academicos#presenciales', :as => :presenciales
    get 'electronicos' => 'programas_academicos#electronicos', :as => :electronicos
    get 'dir-acad-test' => 'informacion_general#directorio_academico', :as => :dir

    get 'calendario-escolar' => 'programas_academicos#calendario_escolar', :as => :calendario

    get 'principios-eticos' => 'principal#principios_eticos', :as => :principios

    get 'resultados_busqueda' => 'principal#resultados_busqueda', :as => :busqueda

    get 'como-llegar' => 'principal#como_llegar', :as =>  :ubicacion

    get 'set_language' => 'principal#set_language', :as => :cambiar_idioma

    get 'directorio_academico_async' => 'informacion_general#directorio_academico_async', :as => :dir_async
    get 'recuperar_docentes' => 'informacion_general#recuperar_docentes', :as => :rec_doc

    get "mapa-sitio" => "principal#sitemap", :as => :sitemap
    get 'proximamente' => 'principal#proximamente', :as => :soon
    get 'aviso-privacidad' => 'principal#aviso_de_privacidad', :as => :aviso
    get 'aviso-completo' => 'principal#aviso_completo', :as => :priv
    get 'aviso-simple' => 'principal#aviso_simple', :as => :priv_simple

    scope "editable" do
      get 'sobre' => 'informacion_general#sobre_el_colegio', :as => :sobre_el_colegio_edit
      get 'historia' => 'informacion_general#historia', :as => :historia_edit
      get 'historia-75-aniversario' => 'informacion_general#historia_75_años', :as => :hist_75_edit
      get 'premios-distinciones' => 'informacion_general#premios_y_distinciones', :as => :premios_edit
      get 'principios-eticos' => 'principal#principios_eticos', :as => :principios_edit
      get 'bienes' => 'informacion_general#bienes', :as => :bienes_edit
      get 'centros' => "centros_de_estudio#inicio", :as => :centros_edit
      get 'programas' => "programas_academicos#inicio", :as => :programas_edit
      get "licenciaturas" => "programas_academicos#licenciaturas", :as => :licenciaturas_edit
      get "maestrias" => "programas_academicos#maestrias", :as => :maestrias_edit
      get "doctorados" => "programas_academicos#doctorados", :as => :doctorados_edit
      get "cursos" => "programas_academicos#cursos", :as => :cursos_edit
      get 'calendario-escolar' => 'programas_academicos#calendario_escolar', :as => :calendario_edit
      get 'admisiones' => "programas_academicos#admisiones", :as => :admisiones_edit
      get 'convocatorias' => 'programas_academicos#convocatorias', :as => :convocatorias_edit
      get 'proceso' => 'programas_academicos#proceso', :as => :proceso_edit
      get 'marco-normativo' => 'informacion_general#marco_normativo', :as => :marco_edit
      get 'autoridades' => 'informacion_general#autoridades', :as => :autoridades_edit
      get 'operativas' => 'informacion_general#operativas', :as => :operativas_edit
      get 'apoyo' => 'informacion_general#unidades_de_apoyo', :as => :unidades_de_apoyo_edit
      get 'administracion' => 'informacion_general#administracion', :as => :administracion_edit
      get 'centros_de_estudio' => 'informacion_general#centros_de_estudio', :as => :centros_autoridades_edit
      get "comision" => "informacion_general#comision", :as => :comision_edit
      get "consejo" => "informacion_general#consejo", :as => :consejo_edit
      get 'presidencia' => 'informacion_general#presidencia', :as => :presidencia_edit
      get 'junta' => 'informacion_general#junta', :as => :junta_edit
    end

  end
 
  get '/:locale' => 'principal#principal', :as => :main

  root to: "principal#principal"

end

app/views/informacion_general/_actas.html.erb
<%  @anios.each do |a| %>
<span class="titulo-grande morado"><%= a %></span>
<br>
<br>

<% @actas.where("anio = ?", a).each do |d| %>

<div class="wrapper-links-doc">
	<div class="img-link-doc">
		<a href=<%= d.liga.to_s == "" ? d.archivo.url : d.liga %> target="_blank" class="uk-link"><img src=<%= image_url("documento.png") %> alt="documento" class="documento uk-vertical-align-middle"></a>
	</div>
	<div class="liga-doc">
		<a href=<%= d.liga.to_s == "" ? d.archivo.url : d.liga %> target="_blank" class="documento uk-link"><%= (params[:locale] == "es" ? d.nombre.gsub(/<\/?p>/,"").mb_chars : d.nombre_eng.gsub(/<\/?p>/,"").mb_chars) %></a>
	</div>
</div>
<% end %>
<br>
<br>
<br>
<% end %>

app/views/informacion_general/_administracion.html.erb
<%= form_for(@sitio, :url => {:controller => "panel", :action => "editar", :params => {:set => "Contenido de sitios", :id => @sitio.id}, :uri => request.original_fullpath.gsub(/editable\/administracion/,"autoridades")}, :html => { :multipart => true }) do |f| %>
  <% if @sitio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sitio.errors.count, "error") %> impidieron generar este objeto:</h2>

      <ul>
      <% @sitio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

<% if @editable %>
	<% @admins.each_with_index do |d,i| %>
	<%= fields_for "listings[]", @listings[i] do |l| %>
	<div class="wrapper-links-doc">
		<%= l.hidden_field :ord_index, value: i %>
		<%= l.select(:list_id,options_for_select(@admins.map{|d| [d.nombre.gsub(/<(\/)?div>/,"").html_safe,d.id]}, @listings[i].list_id || @admins[i].id), {}, {}) %>
	</div>
	<% end %>
	<% end %>

<% else %>

	<% @sitio = Sitio.where("ref = ? ","Autoridades (administración)").first %>
	<% @lists = Listing.where("sitio_id = ?",@sitio.id).order(:ord_index).pluck(:list_id) %>
	<% @lists.each do |l| %>
		<% a = Personal.find(l) %>

    <div class="uk-margin-large-bottom">
    <h4><%= (params[:locale] == "es" ? a.cargo.mb_chars.upcase : a.cargo_eng.mb_chars.upcase ) %></h4>
    <h3 class="vino"><%= a.nombre %></h3>
    <p class="izq-align"><%= t('sobre.autoridades.correo') %>: <a class="uk-link" href="mailto:<%= a.correo %>"><%= a.correo %></a></p>
    <p class="izq-align"><%= t('sobre.autoridades.tel') %>: <%= a.telefono %></p>
    <p class="izq-align"><%= t('sobre.autoridades.ext') %>: <%= a.extension %></p>
    </div>
    <% end %>
<% end %>

<% if @editable %>
<div class="actions">
	<%= f.submit "Guardar cambios" %>
</div>

<% end %>
<% end %>

app/views/informacion_general/_asamblea.html.erb
<p>&nbsp;</p>    
<div class="uk-grid uk-grid-large" data-uk-grid-match>
    <div class="uk-width-1-2 uk-text-center">
    <a href="http://www.gob.mx/sep" target="_blank">
    <img src=<%= image_url("sep.png") %> alt="Secretaría de Educación Pública" width="505" height="220"><br>
    </a>
    </div>
    <div class="uk-width-1-2 uk-text-center">
    <a href="https://www.unam.mx/" target="_blank">
    <img src=<%= image_url("unam.png") %> alt="Universidad Nacional Autónoma de México" width="505" height="220"><br>
    </a>
    </div>
    </div>
    <p>&nbsp;</p>
    <div class="uk-grid uk-grid-large" data-uk-grid-match>
    <div class="uk-width-1-2 uk-text-center">
    <a href="http://www.banxico.org.mx/" target="_blank">
    <img src=<%= image_url("banxico.png") %> alt="Banco de México"  width="393" height="220"><br>
    </a>
    </div>
    <div class="uk-width-1-2 uk-text-center">
    <a href="https://www.fondodeculturaeconomica.com/" target="_blank">
    <img src=<%= image_url("fondo-cultura-economica.png") %> alt="Fondo de Cultura Económica" width="505" height="220"><br>
    </a>
    </div>
    </div>

app/views/informacion_general/_comision.html.erb
<%= form_for(@sitio, :url => {:controller => "panel", :action => "editar", :params => {:set => "Contenido de sitios", :id => @sitio.id}, :uri => request.original_fullpath.gsub(/editable\/comision/,"autoridades")}, :html => { :multipart => true }) do |f| %>
  <% if @sitio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sitio.errors.count, "error") %> impidieron generar este objeto:</h2>

      <ul>
      <% @sitio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

<% if @editable %>
	<% @coms.each_with_index do |d,i| %>
	<%= fields_for "listings[]", @listings[i] do |l| %>
	<div class="wrapper-links-doc">
		<%= l.hidden_field :ord_index, value: i %>
		<%= l.select(:list_id,options_for_select(@coms.map{|d| [d.nombre.gsub(/<(\/)?div>/,"").html_safe,d.id]}, @listings[i].list_id || @coms[i].id), {}, {}) %>
	</div>
	<% end %>
	<% end %>

<% else %>

	<% @sitio = Sitio.where("ref = ? ","Autoridades (comisión)").first %>
	<% @lists = Listing.where("sitio_id = ?",@sitio.id).order(:ord_index).pluck(:list_id) %>
	<% @lists.each do |l| %>
		<% c = Personal.find(l) %>
    	<h4><%= c.nombre %></h4>
    <% end %>
<% end %>

<% if @editable %>
<div class="actions">
	<%= f.submit "Guardar cambios" %>
</div>

<% end %>
<% end %>

app/views/informacion_general/_consejo.html.erb
<%= form_for(@sitio, :url => {:controller => "panel", :action => "editar", :params => {:set => "Contenido de sitios", :id => @sitio.id}, :uri => request.original_fullpath.gsub(/editable\/consejo/,"autoridades")}, :html => { :multipart => true }) do |f| %>
  <% if @sitio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sitio.errors.count, "error") %> impidieron generar este objeto:</h2>

      <ul>
      <% @sitio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

<% if @editable %>
	<% i = 0 %>

	<% @deptos.each do |d| %>
		<h3 style="margin-top:25px;margin-bottom:15px;"><%= d.mb_chars.upcase %></h3>
		<% condicion = (params[:locale] == "es" ? "depto = ?" : "depto_eng = ?") %>
		<% @consejo.where(condicion,d).each do |c| %>
			<%= fields_for "listings[]", @listings[i] do |l| %>
				<div class="wrapper-links-doc">
					<%= l.hidden_field :ord_index, value: i %>
					<%= l.select(:list_id,options_for_select(@consejo.map{|d| [d.nombre.gsub(/<(\/)?div>/,"").html_safe,d.id]}, @listings[i].list_id || @consejo[i].id), {}, {}) %>
				</div>
				<% i = i + 1 %>
			<% end %>
		<% end %>

	<% end %>

<% else %>

	<% @sitio = Sitio.where("ref = ? ","Autoridades (consejo)").first %>
	<% @lists = Listing.where("sitio_id = ?",@sitio.id).order(:ord_index).pluck(:list_id) %>
	<% @it = 0 %>

	<% if false %>
  <% @deptos.each do |d| %>
    <h3 style="margin-top:25px;margin-bottom:15px;"><%= d.mb_chars.upcase %></h3>
		<% condicion = (params[:locale] == "es" ? "depto = ?" : "depto_eng = ?") %>
		<% @consejo.where(condicion,d).each do |c| %>
			<h5 style="margin-top:10px;margin-bottom:0px;"><%= c.nombre.mb_chars %></h5>
		<% end %>
  <% end %>
	<% end %>

  <% @deptos.each_with_index do |d,j| %>
		  <h3 style="margin-top:25px;margin-bottom:15px;"><%= d.mb_chars.upcase %></h3>
			<% condicion = (params[:locale] == "es" ? "depto = ?" : "depto_eng = ?") %>
			<% @totals[j].times do |co| %>
				<% c = Personal.find(@lists[@it]) %>
				<h5 style="margin-top:10px;margin-bottom:0px;"><%= c.nombre.mb_chars %></h5>
				<% @it = @it + 1 %>
			<% end %>
  <% end %>

<% end %>

<% if @editable %>
<div class="actions">
	<%= f.submit "Guardar cambios" %>
</div>

<% end %>
<% end %>

app/views/informacion_general/actas.js.erb
$("#titulo-render").html("<%= t('sobre.documentacion.op1') %>");
$("#documentacion-render").html("<%= j render :partial => 'actas' %>");

app/views/informacion_general/autoridades.html.erb
<%= render 'principal/barra' %>
<div class="container-fluid" id="resto-cuerpo">
	<div id="cuerpo" class="principal-chica uk-block-large">

	<div class="uk-width-1-1">
    <div class="uk-grid uk-grid-medium">
    <div class="uk-width-large-2-5 uk-text-center-small uk-text-center-medium uk-text-left" style="border-right: 2px solid #EEEEEE;">
    <span class="titulo-grande"><%= t('botones.b1.opciones.op2') %></span><br>
    <!--          Aquí empieza el menú pequeño          -->
    <ul style="text-align:left;">
    	<li style="list-style-type:none; margin-bottom:5px;"><%= link_to(image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + t('sobre.autoridades.asamblea'), asamblea_path, :remote => true, :class => "link-sobre", :id => "asamblea-link") %></li>
				<li style="list-style-type:none; margin-bottom:5px;"><%= link_to image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + t('sobre.autoridades.junta'), (@editable ? junta_edit_path : junta_path), :remote => true, :class => "link-sobre", :id => "junta-link" %></li>
				<li style="list-style-type:none; margin-bottom:5px;"><%= link_to image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + t('sobre.autoridades.presidencia'), (@editable ? presidencia_edit_path : presidencia_path), :remote => true, :class => "link-sobre", :id => "presidencia-link" %></li>
				<li style="list-style-type:none; margin-bottom:5px;"><%= link_to image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + t('sobre.autoridades.consejo'), (@editable ? consejo_edit_path : consejo_path), :remote => true, :class => "link-sobre", :id => "presidencia-link" %></li>
				<li style="list-style-type:none; margin-bottom:5px;"><%= link_to image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + t('sobre.autoridades.comision'), (@editable ? comision_edit_path : comision_path), :remote => true, :class => "link-sobre", :id => "presidencia-link" %></li>
				<li style="list-style-type:none; margin-bottom:5px;"><%= link_to image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + t('sobre.autoridades.centros'), (@editable ? centros_autoridades_edit_path : centros_autoridades_path), :remote => true, :class => "link-sobre", :id => "centros-link" %></li>
				<li style="list-style-type:none; margin-bottom:5px;"><%= link_to image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + t('sobre.autoridades.admin'), (@editable ? administracion_edit_path : administracion_path), :remote => true, :class => "link-sobre", :id => "administracion-link" %></li>
				<li style="list-style-type:none; margin-bottom:5px;"><%= link_to image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + t('sobre.autoridades.apoyo'), (@editable ? unidades_de_apoyo_edit_path : unidades_de_apoyo_path), :remote => true, :class => "link-sobre", :id => "biblioteca-link" %></li>
				<li style="list-style-type:none; margin-bottom:25px;"><%= link_to image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + t('sobre.autoridades.operativas'), (@editable ? operativas_edit_path : operativas_path), :remote => true, :class => "link-sobre", :id => "operativas-link" %></li>
    </ul>
    <!--          Aquí termina el menú pequeño          -->
    </div>
    <div class="uk-width-large-3-5">
			<span class="titulo-grande morado" id="titulo-render"><%= t('sobre.autoridades.asamblea') %></span>
			<div id="autoridades-render" style="padding-top: 15px;">
				<%= render "informacion_general/asamblea" %>
			</div>
		</div>
		</div>
	</div>
	</div>
<%= render 'principal/footer' %>

app/views/informacion_general/biblioteca.js.erb
$("#titulo-render").html("<%= t('sobre.autoridades.biblioteca') %>");
$("#autoridades-render").html("<%= j render :partial => 'biblioteca' %>");

app/views/informacion_general/bienes.js.erb
$("#titulo-render").html("<%= "Relación de bienes muebles e inmuebles" %>");
$("#transp-render").html("<%= j render :partial => 'bienes' %>");

app/views/informacion_general/centros_de_estudio.js.erb
$("#titulo-render").html("<%= t('sobre.autoridades.centros') %>");
$("#autoridades-render").html("<%= j render :partial => 'centros_de_estudio' %>");

app/views/informacion_general/directorio_institucional.html.erb
<%= render 'principal/barra' %>

<%= include_gon %>

<div class="container-fluid" id="resto-cuerpo">
	<div id="cuerpo" class="principal-chica uk-block-large">

		<div class="row">
			<div class="col-xs-12" style="padding-left:0;">
				<span class="titulo-grande">Directorio institucional</span><br>
			</div>
			<div class="col-xs-12" style="padding-left:0;">
				<p style="margin-top:25px;margin-bottom:25px">Aquí podrás encontrar información de contacto de los integrantes de El Colegio de México.</p>
			</div>
		</div>

		<div class="row" id="filtros-dir">
			<div class="col-xs-12" style="padding-left:0;">
				<h3>Buscar por orden alfabético.</h3>
			</div>
			<div class="col-xs-12" id="filtro-inic" style="text-align:center;padding-left:0;">
			<% for i in 65..90 %>
				<span class="inics letra" id=<%= "inic_" + i.chr %> style="cursor:pointer; margin:0 3px;font-size:24px;color:#909090;" onclick=<%= "filtrarDirectorio('" + i.chr + "')" %>><%= i.chr %></span>
			<% end %>
			</div>
			<div class="col-md-4 col-xs-12 filtro center" id="filtro-nombre">
				<h3 style="display:inline-block;margin-right:8px;">Buscar por:</h3><%= text_field_tag("nombre", "", :oninput => "filtrarDirectorio();", :placeholder => "Nombre") %>
			</div>
			<div class="col-md-4 col-xs-12 center" id="filtro-linea" style="padding-left:15px;">
				<%= select_tag("centro", options_for_select(@centros), :include_blank => "Centro", :onchange => "filtrarDirectorio();") %><br>

			</div>
			<div class="col-md-4 col-xs-12 center" id="filtro-mail" style="padding-left:15px;">
				<%= select_tag("rol", options_for_select(@roles), :include_blank => "Todos", :onchange => "filtrarDirectorio();") %><br>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12 col-md-4 center" id="filtro-centro">
				<% if false %>
				<h3 style="display:inline-block;margin-right:8px;">Filtrar por:</h3><%= select_tag("contenido", options_for_select(@centros), :include_blank => "Centro", :onchange => "filtrarDirectorio();") %>
				<% end %>
			</div>
			<div class="col-xs-12 col-md-4 center" id="filtro-limpiar" style="text-align:left;">
				<div id="boton_limpiar">
					<a href="#" onclick="borrarDocentes(event);" class="boton-donar"><span><%= "Limpiar búsqueda" %></span></a>
				</div>
			</div>
		</div>

		<div class="row">
			<% if false %>
				<script type="text/javascript" src="../js/accordion.js"></script>
			<% end %>
			<div class="col-xs-12" style="text-align:left;padding-top:20px;" id="filete-top">
				<h2 id="frase-linea"></h2>
			</div>
			<div class="col-xs-12 acordeon-premios" id="busqueda">
				<%= construirMiembros(@miembros) %>
			</div>
		</div>
		<div id="separadores" style="text-align:center;margin:10px auto;">
		</div>
	</div>

<script type="text/javascript" src="../js/filtro_dir_inst.js"></script>
<script type="text/javascript">
	actualizarVisibleDirectorio([]);
</script>
<%= render 'principal/footer' %>

app/views/informacion_general/estatutos.js.erb
$("#titulo-render").html("<%= t('sobre.documentacion.op3') %>");
$("#documentacion-render").html("<%= j render :partial => 'estatutos' %>");

app/views/informacion_general/premios_y_distinciones.html.erb
<%= render 'principal/barra' %>

<div class="container-fluid" id="resto-cuerpo">
	<div id="cuerpo" class="principal uk-block-large">

    <div class="uk-width-1-1">
        <span class="titulo-grande"><%= t('botones.b1.opciones.op6') %></span><br>
    <div class="uk-container-center uk-block"><img src=<%= image_url("premios-nueva.jpg") %> alt="Cursos"></div>
    <p>&nbsp;</p>
    <div class="uk-grid uk-grid-medium">
    <div class="uk-width-large-1-5 uk-text-center-small uk-text-center-medium uk-text-left" style="border-right:2px solid #EEEEEE;">
    <!--          Aquí empieza el menú pequeño          -->
    <ul style="text-align:left;">
      <li style="list-style-type:none; margin-bottom:5px;"><%= link_to(image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + (params[:locale] == "en" ? "Awarded to the community" : "Otorgados a la comunidad"), otorgadoscomunidad_path, :remote => true, :class => "link-sobre", :id => "presencial-link") %></li>
      <li style="list-style-type:none; margin-bottom:5px;"><%= link_to image_tag('bt-flechita.png', :class => "leave_img") + image_tag("bt-flechita-hover.png", :class => "hover_img") + (params[:locale] == "en" ? "Given by El Colegio" : "Otorgados por El Colegio"), otorgadoscolegio_path, :remote => true, :class => "link-sobre", :id => "electronico-link" %></li>
    </ul>
    </div>

    <div class="uk-width-large-4-5">
    <span class="titulo-chico morado" id="titulo-render"><%= params[:locale] == "en" ? "Prizes awarded to the community and members of El Colegio de México" : "Premios otorgados a la comunidad" %></span><br>

    <div id="premios-render">
    	<%= render 'informacion_general/comunidad' %>

    </div>
    </div>
    </div>
    </div>

	</div>


<%= render 'principal/footer' %>